steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - '-f'
      - Dockerfile
      - --build-arg NEXT_PUBLIC_MAPS_KEY=$$NEXT_PUBLIC_MAPS_KEY
      - --build-arg NEXT_PUBLIC_URL=$$NEXT_PUBLIC_URL
    secretEnv: ['NEXT_PUBLIC_MAPS_KEY', 'NEXT_PUBLIC_URL']
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
      - --set-env-vars NEXT_PUBLIC_MAPS_KEY=$$NEXT_PUBLIC_MAPS_KEY
      - --set-env-vars NEXT_PUBLIC_URL=$$NEXT_PUBLIC_URL
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - visitor-ui
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/maps-key/versions/latest
    env: 'NEXT_PUBLIC_MAPS_KEY'
  - versionName: projects/$PROJECT_ID/secrets/public-url/versions/latest
    env: 'NEXT_PUBLIC_URL'