steps:
- name: 'node'
  entrypoint: 'yarn'
  args: ['install']
- name: 'node'
  entrypoint: 'yarn'
  args: ['build']
  secretEnv: ['NEXT_PUBLIC_URL', 'NEXT_PUBLIC_MAPS_KEY']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
  secretEnv: ['NEXT_PUBLIC_URL', 'NEXT_PUBLIC_MAPS_KEY']
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/public-url/versions/1
    env: 'NEXT_PUBLIC_URL'
  - versionName: projects/$PROJECT_ID/secrets/maps-key/versions/latest
    env: 'NEXT_PUBLIC_MAPS_KEY'