steps:
- name: 'node'
  entrypoint: 'yarn'
  args: ['install']
- name: 'node'
  entrypoint: 'yarn'
  args: ['build']
  env: 
  - 'NEXT_PUBLIC_MAPS_KEY=$_MAPS_KEY'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY