import { useMemo } from "react";
import { IPlace } from "PlacesClient/index";
import { GeoCoordinate } from "Types/Geolocation";

export const useExploreData = (places: Pick<IPlace, PlaceKeys>[]) => {
  return useMemo(() => {
    const results: FormattedPlace[] = [];
    for (const place of places) {
      if (!place.id) {
        continue;
      }
      const photos: string[] = [];
      const photoList = place.photos ?? [];
      for (const photo of photoList) {
        if (photo.name) {
          photos.push(photo.name);
        }
      }
      results.push({
        photos,
        id: place.id,
        rating: place.rating,
        website: place.websiteUri,
        location: place.location as unknown as GeoCoordinate,
        types: place.types ?? [],
        name: place.displayName?.text ?? "",
        address: place.shortFormattedAddress ?? place.formattedAddress ?? "",
        reviewSummary: place.reviewSummary?.text?.text ?? "",
        googleURL: place.googleMapsLinks?.placeUri ?? "",
        directionsURL: place.googleMapsLinks?.directionsUri ?? "",
        reviewsURL: place.googleMapsLinks?.reviewsUri ?? "",
      });
    }
    return results;
  }, [places]);
};

export type PlaceKeys =
  | "id"
  | "displayName"
  | "rating"
  | "location"
  | "formattedAddress"
  | "shortFormattedAddress"
  | "types"
  | "photos"
  | "reviewSummary"
  | "websiteUri"
  | "googleMapsLinks";

export const FIELD_MASK =
  "places.id,places.displayName.text,places.rating,places.formattedAddress,places.shortFormattedAddress,places.types,places.location,places.photos.name,places.reviewSummary.text,places.websiteUri,places.googleMapsLinks.directionsUri,places.googleMapsLinks.placeUri,places.googleMapsLinks.reviewsUri";

export interface FormattedPlace {
  id: string;
  photos: string[];
  types: string[];
  name: string;
  rating?: number;
  location?: GeoCoordinate;
  address: string;
  website?: string;
  reviewSummary?: string;
  googleURL: string;
  reviewsURL: string;
  directionsURL: string;
}

export const SKELETON_DATA: FormattedPlace[] = new Array(6).fill({
  photos: [""],
  id: "-1",
  rating: 0,
  website: "",
  types: ["loading", "loading", "loading"],
  name: "Loading Place Name",
  address: "",
  reviewSummary:
    "Loading a review generated by AI. The AI summarizes the most common observed patterns in customer reviews and presents them in a precise and simple fashion",
  googleURL: "",
  directionsURL: "",
  reviewsURL: "",
  loading: true,
  location: { latitude: 0, longitude: 0 },
});
